### ISSUE TITLE
Failed to precompile derry in Flutter 2.2.0

### ISSUE THREAD

**Issue by Brazol** [frencojobs/derry#49] opened 2021-05-26 13:43 UTC
I get this error when trying to activate derry after upgrading to Flutter 2.2.0

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/5622717/119670200-fc94fa80-be38-11eb-9b94-aaf12accefb2.png">

**Comment by xalikoutis** [comment] 2021-05-31 08:43
same here

**Comment by frencojobs** [comment] 2021-06-14 09:50
Duplicate of #47

**Closed by frencojobs** 2021-06-14 09:50 UTC
