### ISSUE TITLE
Derry swallows exit codes

### ISSUE THREAD

**Issue by are** [frencojobs/derry#35] opened 2020-11-19 13:31 UTC
Hi there! First of all, thank you so much for developing this tool.

I have a question/bug report - when `derry` runs a script and it fails, instead of returning the exit code of the script it returns `0`. Is this intentional?

If it is intentional, would `derry` benefit from a config/option to enable passing exit codes from scripts?

Please let me know your thoughts. I am willing to create a PR once we settle on a solution.

**Comment by frencojobs** [comment] 2020-11-19 15:12
> thank you so much for developing this tool

Thanks! I appreciated.

> when derry runs a script and it fails, instead of returning the exit code of the script it returns 0. Is this intentional?

No, it is not intentional. I just did not return anything from the rust execution side so the state of execution is not handled at all.

> would derry benefit from a config/option to enable passing exit codes from scripts?

I do think it could be done, but I don't see any benefit though. Or am I missing something? Does it cause fatal errors or have use cases?

**Comment by are** [comment] 2020-11-19 15:35
Thanks for responding so quickly!

> I do think it could be done, but I don't see any benefit though. Or am I missing something? Does it cause fatal errors or have use cases?

So one thing is that when you execute multiple lines in a script (using the array/list syntax) and one of them fails, derry continues executing. This may be undesirable because steps can expect something to happen beforehand and the failure just cascades (and may break things even more).

Second benefit is from using `derry` in automated environments (PS. I know from previous issues that `derry` was supposed to be a developer tool, but I believe this change would add consistency with other tools and improve the overall usability). I would love to use `derry` to run scripts in the CI environment because it makes it so much more readable and sustainable, but `derry` swallowing exit codes makes it impossible to use for running tests or analysis as many CI environments rely on exit codes to signify failure.

**Comment by frencojobs** [comment] 2020-11-19 16:10
Oh, yes I see. That is an excellent reason, and it could be a nice feature to have. I have used it in CI environments but I wasn't aware that it could be a potential problem.

PRs are welcome. But I'm not entirely sure if the rust executor I wrote could return exit codes or not. If it does, the implementation will be pretty much straightforward. If you don't write Rust, let me do that tomorrow morning :alarm_clock:.

**Comment by are** [comment] 2020-11-19 16:18
I am not familiar with Rust enough to do this change, so let me know when you investigate this. If you introduce the necessary changes to Rust I can take it from there if you don't have time or resources and do the Dart part in a PR. Thank you so much for taking your time to do this!

**Comment by frencojobs** [comment] 2020-11-20 12:01
Thank you for your help, but since there wasn't much to do and I also had things to fix myself, I just went ahead and add that feature. It will be in v1.1.0 at #37. Please let me know if you have any errors on the implementation or if it's not as intended.

Just a note that,
> So one thing is that when you execute multiple lines in a script (using the array/list syntax) and one of them fails, derry continues executing

It is intentional. I wanted different steps to have separate execution contexts. What you want can be achieved by doing
```yaml
failable:
  (execution): once
  (scripts):
    - echo test
    - "false"
    - echo "this won't be called"
```
It is kinda ugly but you probably don't have to use it. You can now have separate CI steps for that, derry commands will now return exit codes.

**Closed** 2020-11-20 12:02 UTC
Labels: enhancement
